export enum MessageType {
  OPEN_SIDEPANEL = 'OPEN_SIDEPANEL',
  FILL_FIELDS = 'FILL_FIELDS',
  GET_PASSWORDS = 'GET_PASSWORDS',
  UNLOCK = 'UNLOCK',
  LOCK = 'LOCK',
  GET_STATUS = 'GET_STATUS',
  LOAD_DOMAINS = 'LOAD_DOMAINS',
  CHECK_DOMAIN = 'CHECK_DOMAIN',
  CLOSE_SIDEPANEL = 'CLOSE_SIDEPANEL'
}